name: docscan
description: Document Scanner App with OCR and PDF Export
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Scanner
  document_scanner_flutter: ^0.4.0
  image_picker: ^1.2.1

  # OCR
  google_mlkit_text_recognition: ^0.13.0

  # PDF
  pdf: ^3.11.0
  printing: ^5.14.2

  # Share & Open
  share_plus: ^10.1.4
  open_file: ^3.5.10

  # Gallery Save
  saver_gallery: ^3.0.10

  # Permission
  permission_handler: ^11.4.0
  device_info_plus: ^10.1.0

  # Image processing
  image: ^4.5.4

  # Storage
  path_provider: ^2.1.5

  # UI
  flutter_animate: ^4.5.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
